CechZlodeju/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zlodeji.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

zlodeji/urls.py
from django.urls import path, re_path

from . import views

app_name = 'zlodej'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'statistics/$', views.Statistics.as_view(), name='stat'),
    re_path(r'vybavenie/$', views.VybavenieView.as_view(), name='vybavenie'),
    re_path(r'povolenia/$', views.Povolenia.as_view(), name='povolenia'),
    re_path(r'register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'login/$', views.LogInView.as_view(), name='login'),
    re_path(r'logout/$', views.LogOutView.as_view(), name='logout'),

    re_path(r'zlodej/add/$', views.ZlodejCreate.as_view(), name='zlodej-add'),
    re_path(r'zlocin/add/$', views.ZlocinCreate.as_view(), name='zlocin-add'),
    re_path(r'urobil/add/$', views.UrobilCreate.as_view(), name='urobil-add'),
    re_path(r'bolna/add/$', views.BolNaCreate.as_view(), name='bolna-add'),
    re_path(r'dostal/add/$', views.DostalCreate.as_view(), name='dostal-add'),
    re_path(r'povolenie/add/$', views.PovolenieCreate.as_view(), name='povolenie-add'),
    re_path(r'lupeznik/add/$', views.VydriduchCreate.as_view(), name='vydriduch-add'),
    re_path(r'vydriduch/add/$', views.LupeznikCreate.as_view(), name='lupeznik-add'),
    re_path(r'vlastnil/add/$', views.VlastnilCreate.as_view(), name='vlastnil-add'),
    re_path(r'vlastnilzlodej/add$', views.VlastnilCreatezlodej.as_view(), name='vlastnil-addzlodej'),
    re_path(r'skolenie/add/$', views.SkolenieCreate.as_view(), name='skolenie-add'),
    re_path(r'skolenieZ/add/$', views.SkolenieZlocinuCreate.as_view(), name='skoleniezlocinu-add'),
    re_path(r'skolenieV/add/$', views.SkolenieVybaveniaCreate.as_view(), name='skolenievybavenia-add'),
    re_path(r'vybavenie/add/$', views.VybavenieCreate.as_view(), name='vybavenie-add'),
    re_path(r'rajon/add/$', views.RajonCreate.as_view(), name='rajon-add'),
    re_path(r'eviduje/add/$', views.EvidujeCreate.as_view(), name='eviduje-add'),
    re_path(r'eviduje/assign/$', views.EvidujeAssign.as_view(), name='eviduje-assign'),
    re_path(r'rajon/(?P<pk>[0-9]+)/$', views.RajonDetail.as_view(), name='rajon-detail'),
    re_path(r'skolenia/$', views.Skolenia.as_view(), name='skolenia'),

    re_path(r'rajony/$', views.DetailView.as_view(), name='detail'),
    re_path(r'zlodej/(?P<pk>[a-zA-Z]+)/staff/$', views.User_Staff.as_view(), name='staff'),
    re_path(r'zlodej/(?P<pk>[a-zA-Z]+)/super/$', views.User_Super.as_view(), name='superuser'),
    re_path(r'zlodej/(?P<pk>[a-zA-Z]+)/$', views.ZlodejUpdate.as_view(), name='zlodej-update'),
    re_path(r'vybavenie/(?P<pk>[a-zA-Z]+)/$', views.VybavenieUpdate.as_view(), name='vybavenie-update'),
    re_path(r'zlocin/(?P<pk>[0-9]+)/$', views.ZlocinUpdate.as_view(), name='zlocin-update'),
    re_path(r'urobil/(?P<pk>[a-zA-Z]+)/$', views.UrobilUpdate.as_view(), name='urobil-update'),
    re_path(r'skolenie/(?P<pk>[0-9]+)/$', views.SkolenieUpdate.as_view(), name='skolenie-update'),

    re_path(r'zlocin/(?P<pk>[a-zA-Z]+)/delete/$', views.ZlocinDelete.as_view(), name='zlocin-delete'),
    re_path(r'urobil/(?P<pk>[0-9]+)/delete/$', views.UrobilDelete.as_view(), name='urobil-delete'),
    re_path(r'dostal/(?P<pk>[0-9]+)/delete/$', views.DostalDelete.as_view(), name='dostal-delete'),
    re_path(r'eviduje/(?P<pk>[0-9]+)/delete/$', views.EvidujeDelete.as_view(), name='eviduje-delete'),
    re_path(r'vlastnil/(?P<pk>[0-9]+)/delete/$', views.VlastnilDelete.as_view(), name='vlastnil-delete'),


    re_path(r'skolenie/(?P<pk>[0-9]+)/approve/$', views.SkolenieApprove.as_view(), name='approve'),
    re_path(r'skolenie/(?P<pk>[0-9]+)/(?P<zlodej>[a-zA-Z]+)/$', views.BolnaCreate.as_view(), name='skolenie-assign'),

]

zlodeji/forms.py
from .models import Zlodej as User
from .models import *
from django import forms
from django.contrib.admin import widgets


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(help_text="Prezívka a Použivateľské meno musia byť rovnaké!")
    prezivka = forms.CharField(help_text="Prezívka a Použivateľské meno musia byť rovnaké!")

    class Meta:
        model = User
        fields = ['username', 'email', 'prezivka', 'meno', 'password',
                  'rc', 'fotka', 'zivy']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-lg'

    def clean(self):
        username = self.cleaned_data.get('username')
        prezivka = self.cleaned_data.get('prezivka')

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            pass

        if prezivka != username:
            self.add_error('username', u"Prezívka a Použivateľské meno musia byť rovnaké!")
            self.add_error('prezivka', u"Prezívka a Použivateľské meno musia byť rovnaké!")

        if username == User.objects.get(username=username).username:
            self.add_error('username', u"Uživateľ " + username + " už existuje!")


class LoginForm(forms.ModelForm):
    username = forms.CharField(label=u"Prihlasovacie meno", help_text=u"Povinné. 150 znakov alebo menej. Môže obsahovať iba písmená, čísla a znaky @/./+/-/_ výhradne.")
    password = forms.CharField(label="Heslo", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VlastnilForm(forms.ModelForm):
    od = forms.DateField(widget=widgets.AdminDateWidget)
    do = forms.DateField(widget=widgets.AdminDateWidget)

    class Meta:
        model = Vlastnil
        fields = ['prezivka', 'id_vybavenia', 'od', 'do']


class VlastnilFormzlodej(forms.ModelForm):

    class Meta:
        model = Vlastnil
        fields = ['prezivka', 'id_vybavenia', 'od', 'do']
        exclude = ('prezivka',)

    def __init__(self, *args, **kwargs):
        self.prezivka = kwargs['initial']['prezivka']
        super(VlastnilFormzlodej, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(VlastnilFormzlodej, self).save(False)
        obj.prezivka = self.prezivka
        commit and obj.save()
        return obj


class EvidujeForm(forms.ModelForm):
    # prezivka = forms.ModelChoiceField(queryset=Zlodej.objects.filter(username=))
    class Meta:
        model = Eviduje
        fields = '__all__'
        exclude = ('prezivka',)
        widgets = {
        }

    def __init__(self, *args, **kwargs):
        self.prezivka = kwargs['initial']['prezivka']
        super(EvidujeForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(EvidujeForm, self).save(False)
        obj.prezivka = self.prezivka
        commit and obj.save()
        return obj

zlodeji/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Count
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .forms import *
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum


class IndexView(generic.ListView):
    template_name = 'zlodeji/index.html'

    def get_queryset(self):
        return Zlocin.objects.all()

    def list_of_korist(self, request):
        username = request.user.username
        return username

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['all_zlodejs'] = Zlodej.objects.all()
        context['urobil'] = Urobil.objects.all()
        context['all_zlocin'] = Zlocin.objects.all()
        context['dostal'] = Dostal.objects.all()
        context['eviduje'] = Eviduje.objects.all()
        context['vlastnil'] = Vlastnil.objects.all()
        context['bolna'] = BolNa.objects.all()
        context['all_vydriduch'] = Vydriduch.objects.all()
        context['all_lupeznik'] = Lupeznik.objects.all()
        return context


class DetailView(generic.ListView):
    model = Zlocin
    template_name = 'zlodeji/detail.html'
    queryset = Zlocin.objects.all()

    # @login_required(login_url='zlodeji/login.html')
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['all_zlodejs'] = Zlodej.objects.all()
        context['zlodej_count'] = Zlodej.objects.count()
        context['zlocin_count'] = Urobil.objects.count()
        context['skolenie_count'] = BolNa.objects.count()
        context['vybavenie_count'] = Vlastnil.objects.count()
        context['urobil'] = Urobil.objects.all()
        context['urobil_unique'] = Urobil.objects.values('prezivka').distinct()
        context['bolna_unique'] = BolNa.objects.values('prezivka').distinct()
        context['vlastnil_unique'] = Vlastnil.objects.values('prezivka').distinct()
        context['dostal_unique'] = Dostal.objects.values('prezivka').distinct()
        context['all_zlocin'] = Zlocin.objects.all()
        context['vlastnil'] = Vlastnil.objects.all()
        context['bolna'] = BolNa.objects.all()
        context['dostal'] = Dostal.objects.all()
        context['typ_vybavenia'] = TypVybavenia.objects.all()
        return context


class ZlodejCreate(LoginRequiredMixin, CreateView):
    template_name = 'zlodeji/registration_form.html'
    model = Zlodej
    fields = ['username','email', 'prezivka','meno', 'password', 'odmena',
                  'rc', 'fotka', 'zivy']


class ZlodejUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    template_name = 'zlodeji/zlodej_form.html'
    model = Zlodej
    fields = ['email','meno', 'odmena', 'rc', 'fotka', 'zivy']
    success_message = u"Uživateľ bol úspešne upravený."


class ZlodejDelete(LoginRequiredMixin, DeleteView):
    model = Zlodej
    success_url = reverse_lazy('zlodej:index')


class ZlocinCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Zlocin
    fields = ['hodnota_korist', 'uspech', 'id_typu_zlocinu']
    success_message = u"Záznam zločinu bol úspešne vytvorený."


class SkolenieCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Skolenie
    fields = ['level_skoleni', 'schvalene', 'poznamky']
    success_message = u"Záznam školenia bol úspešne vytvorený."


class SkolenieUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Skolenie
    fields = ['level_skoleni', 'schvalene', 'poznamky']
    success_message = u"Záznam školenia bol úspešne vytvorený."


class VybavenieCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Vybavenie
    fields = ['meno', 'id_typu_vybavenia']
    success_message = u"Záznam bol úspešne vytvorený."


class VybavenieUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Vybavenie
    fields = ['meno', 'id_typu_vybavenia']
    success_message = u"Záznam bol úspešne vytvorený."


class ZlocinUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Zlocin
    fields = ['hodnota_korist', 'uspech', 'id_typu_zlocinu']
    success_message = u"Záznam bol úspešne vytvorený."


class ZlocinDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Zlocin
    success_message = u"Záznam bol úspešne odstránený."
    success_url = reverse_lazy('zlodej:index')

class UrobilDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Urobil
    success_message = u"Záznam bol úspešne odstránený."
    success_url = reverse_lazy('zlodej:index')


class BolnaCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = BolNa
    fields = ['id_skolenia', 'prezivka']
    success_message = u"Záznam bol úspešne vytvorený."



class BolnaUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = BolNa
    fields = ['id_skolenia', 'prezivka']
    success_message = u"Záznam bol úspešne upravený."


class UrobilCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Urobil
    fields = ['id_zlocinu', 'prezivka']
    success_message = u"Záznam bol úspešne vytvorený."



class UrobilUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Urobil
    fields = ['id_zlocinu', 'prezivka']
    success_message = u"Záznam bol úspešne upravený."


class VlastnilCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    form_class = VlastnilForm
    template_name = 'zlodeji/vlastnil_form.html'
    success_message = u"Záznam bol úspešne vytvorený."


class VlastnilUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    form_class = VlastnilForm
    template_name = 'zlodeji/vlastnil_form.html'
    success_message = u"Záznam bol úspešne upravený."



class Skolenia(generic.ListView):
    template_name = 'zlodeji/skolenia.html'

    def get_queryset(self):
        return BolNa.objects.all()

    def get_context_data(self, **kwargs):
        context = super(Skolenia, self).get_context_data(**kwargs)
        context['all_zlodejs'] = Zlodej.objects.all()
        context['zlodej_count'] = Zlodej.objects.count()
        context['zlocin_count'] = Urobil.objects.count()
        context['skolenie_count'] = BolNa.objects.count()
        context['vybavenie_count'] = Vlastnil.objects.count()
        context['sk_zlocinu_count'] = SkolenieZlocinu.objects.count()
        context['sk_zlocinu'] = SkolenieZlocinu.objects.all()
        context['sk_vybavenia_count'] = SkolenieVybavenia.objects.count()
        context['sk_vybavenia'] = SkolenieVybavenia.objects.all()
        context['urobil'] = Urobil.objects.all()
        context['urobil_unique'] = Urobil.objects.values('prezivka').distinct()
        context['bolna_unique'] = BolNa.objects.values('prezivka').distinct()
        context['vlastnil_unique'] = Vlastnil.objects.values('prezivka').distinct()
        context['all_zlocin'] = Zlocin.objects.all()
        context['dostal'] = Dostal.objects.all()
        context['eviduje'] = Eviduje.objects.all()
        context['vlastnil'] = Vlastnil.objects.all()
        context['bolna'] = BolNa.objects.all()
        return context


class RegisterView(View):
    form_class = UserForm
    template_name = 'zlodeji/registration_form.html'

    # display form
    def get(self, request):
        form = self.form_class(initial={'odmena': '0',})
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # clean data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, u"Vitaj " + username + "!")
                    return redirect('zlodej:index')

        return render(request, self.template_name, {'form': form})


class LogInView(SuccessMessageMixin, View):
    form_class = LoginForm
    template_name = 'zlodeji/login_form.html'

    # display form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(None)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, u"Vitaj späť " + username + "!")
                return redirect('zlodej:index')
        return render(request, self.template_name, {'form': form})


class LogOutView(LoginRequiredMixin, View):

    # process form data
    def get(self, request):
        logout(request)
        messages.success(request, u"Odhlásenie prebehlo úspešne!")
        return redirect('zlodej:index')


class SkolenieApprove(LoginRequiredMixin, UpdateView):
    model = Skolenie
    fields = ['schvalene']
    success_url = reverse_lazy('zlodej:skolenia')


class User_Super(LoginRequiredMixin, UpdateView):

zlodeji/templates/zlodeji/album_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'zlodeji/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

zlodeji/templates/zlodeji/dostal_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Priradiť povolenie na zločin{% endblock %}
{% block albums_active %}active{% endblock %}
{% load widget_tweaks %}
{% block body %}
    <div class="container-fluid">

        <div class="row" style="width: 50%; margin: 0 auto; text-align: center;">

            <div class="col-xs-12">
                <div class="panel-body">
                    <h3>Evidovať povolenie</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'zlodeji/form-template.html' %}
                        <div class="form-group">
                            <div class="">
                                <button type="submit" class="btn btn-success">Potvrdiť</button>
                            </div>
                        </div>
                        <div class="">
                                <button type="button" class="btn btn-info" onclick="window.location.href = '{% url 'zlodej:povolenie-add' %}'">
                                    Vytvoriť nové povolenie
                                </button>
                            </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

zlodeji/templates/zlodeji/login_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Login{% endblock %}
{% block albums_active %}active{% endblock %}
{% load widget_tweaks %}
{% block body %}

    <div id="id01" class="modal" style="margin: 0 auto; text-align: center;">
        <span id="xclose" onclick="document.getElementById('id01').style.display='none'" class="login close">×</span>
        <form class="form-horizontal container modal-content" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group col-xs-12">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                                <div class="invalid-feedback" style="color: red;">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% else %}
                            {% render_field field class="form-control is-valid" %}
                        {% endif %}
                    {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-offset-12 col-sm-12">
                    <button type="submit" class="btn-reg btn-success">Prihlásiť</button>
                </div>
                <div class="col-sm-12">
                    <button type="button" onclick="window.location.href = '{% url 'zlodej:register' %}'"
                            class="btn-reg btn-info">
                        Zaregistrovať nového uživateľa
                    </button>
                </div>
            </div>
        </form>
    </div>

    <script>
        // Get the modal
        var modal = document.getElementById('id01');
        var close = document.getElementById('xclose');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
                window.location.href = "{% url 'zlodej:index' %}";
            }
            if (event.target === close) {
                window.location.href = "{% url 'zlodej:index' %}";
            }
        }
    </script>

{% endblock %}

zlodeji/templates/zlodeji/lupeznik_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Priradiť vybavenie{% endblock %}
{% block albums_active %}active{% endblock %}
{% load widget_tweaks %}
{% block body %}
    <div class="container-fluid">

        <div class="row" style="width: 50%; margin: 0 auto; text-align: center;">
            <h3>Vytvoriť lupežníka</h3>

            <div class="col-xs-12">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'zlodeji/form-template.html' %}
                        <div class="form-group">
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-success">Potvrdiť</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

zlodeji/templates/zlodeji/povolenia.html
{% extends 'zlodeji/base.html' %}
{% block title %}Povolenia{% endblock %}
{% load static %}
{% block body %}

    <div class="page-header center">
        <h1 style="padding-left: 40%;">Povolenia</h1>
        <p style="padding-left: 35%;">Zoznam aktuálne dostupných povolení na vykonanie zločinu.</p>
    </div>

    <div class="container">

        <div class="panel-body">
            {% if dostal %}
                <table class="table table-striped table-bordered table-list">
                <thead>
                <tr>
                    <th align="center">
                        Rajon
                    </th>
                    <th align="center">Doba platnosti v dňoch</th>
                    <th align="center">Zlodej</th>
                    <th align="center">Druh zločinu</th>
                    {% if user.is_staff %}
                        <th align="center"></th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for povolenie in dostal %}
                    {% if user.is_staff %}
                        <h1></h1>
                        <tr>
                            <td align="center">
                                {{ povolenie.id_povolenia.nazov_rajonu }}
                            </td>
                            <td align="center">
                                {{ povolenie.id_povolenia.doba_platnosti }}
                            </td>
                            <td align="center">{{ povolenie.prezivka }}</td>
                            <td align="center">{{ povolenie.id_povolenia.id_zlocinu.id_typu_zlocinu.druh }}</td>
                            <td align="center">
                                <form action="{% url 'zlodej:dostal-delete' povolenie.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="povolenie_id" value="{{ povolenie.id }}"/>
                                    <button type="submit" class="btn btn-danger btn-xs">
                                        <span class="glyphicon glyphicon-remove"></span>&nbsp;
                                        Odstrániť
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% else %}
                        {% if povolenie.prezivka == user.prezivka %}
                            <h1></h1>
                            <tr>
                                <td align="center">
                                    {{ povolenie.id_povolenia.nazov_rajonu }}

                                </td>
                                <td align="center">
                                    {{ povolenie.id_povolenia.doba_platnosti }}

                                </td>
                                <td align="center">{{ povolenie.prezivka }}</td>
                                <td align="center">{{ povolenie.id_povolenia.id_zlocinu.id_typu_zlocinu.druh }}</td>
                            </tr>
                        {% endif %}
                    {% endif %}

                {% endfor %}
                </tbody>
            {% else %}
                <h3> Nemáte žiadne dostupné povolenia na zločin. Kontaktujte svojho úradníka.</h3>
            {% endif %}

        </div>

{% endblock %}

zlodeji/templates/zlodeji/urobil_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Pridať zločin{% endblock %}
{% block albums_active %}active{% endblock %}
{% load widget_tweaks %}

{% block body %}
    <div class="container-fluid">

        <div class="row" style="width: 50%; margin: 0 auto; text-align: center;">
            <h3>Evidovať zločin</h3>

            <div class="col-xs-12">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" name="form_zlocin">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}

                                {% if form.is_bound %}
                                    {% if field.errors %}
                                        {% render_field field class="form-control is-invalid" %}
                                        {% for error in field.errors %}
                                            <div class="invalid-feedback" style="color: red;">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}

                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-success">
                                    Potvrdiť
                                </button>
                            </div>
                        </div>
                        <div class="">
                            <button type="button" class="btn btn-info" onclick="window.location.href = '{% url 'zlodej:zlocin-add' %}'">
                                Vytvoriť nový zločin
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

zlodeji/templates/zlodeji/vybavenie_form.html
{% extends 'zlodeji/base.html' %}
{% block title %}Priradiť vybavenie{% endblock %}
{% block albums_active %}active{% endblock %}
{% load widget_tweaks %}
{% block body %}
    <div class="container-fluid">

        <div class="row" style="width: 50%; margin: 0 auto; text-align: center;">
            <h3>Vytvoriť vybavenie</h3>

            <div class="col-xs-12">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'zlodeji/form-template.html' %}
                        <div class="form-group">
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-success">Potvrdiť</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}